//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use chrono::DateTime;
use chrono::Utc;
use sea_orm::entity::prelude::*;
use serde::Deserialize;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "ingestion")]
pub struct Model
{
    #[sea_orm(primary_key)]
    pub id: i32,
    pub substance_name: String,
    #[sea_orm(column_type = "custom(\"enum_text\")")]
    pub route_of_administration: String,
    #[sea_orm(column_type = "Float")]
    pub dosage: f32,
    pub notes: Option<String>,
    pub ingested_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub created_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
