#!/bin/sh

echo -e "
   _  __                           __  
  / |/ /__ __ _________  ___  ___ / /__
 /    / -_) // / __/ _ \/ _ \/ -_)  '_/
/_/|_/\__/\_,_/_/  \___/_//_/\__/_/\_\ 
"

BIN_DIR="${XDG_BIN_HOME:-$HOME/.local/bin}"

mkdir -p "$BIN_DIR"

BINARY_PATH="./neuronek"
BINARY_NAME=$(basename "$BINARY_PATH")

cp "$BINARY_PATH" "$BIN_DIR/$BINARY_NAME"
chmod +x "$BIN_DIR/$BINARY_NAME"

echo "$BINARY_NAME has been installed to $BIN_DIR."

# Ensure ~/.local/bin is in the PATH if not already
if ! echo "$PATH" | grep -q "$BIN_DIR"; then
  SHELL_CONFIG_FILE="$HOME/.bashrc"
  
  # Determine which shell configuration file to modify
  if [ -n "$ZSH_VERSION" ]; then
    SHELL_CONFIG_FILE="$HOME/.zshrc"
  fi
  
  echo "Adding $BIN_DIR to your PATH in $SHELL_CONFIG_FILE"
  echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$SHELL_CONFIG_FILE"
  
  echo "Please restart your shell or run 'source $SHELL_CONFIG_FILE' to update your PATH."
fi

echo "------------------------------------------------------------------"

./neuronek
